-- AlterTable
ALTER TABLE "Faq" ADD COLUMN     "category" TEXT NOT NULL DEFAULT 'General',
ADD COLUMN     "isActive" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
